### ISSUE TITLE
User should be able to define own blocks

### ISSUE THREAD

**Issue by TobiasJacob** [IT4Kids/Snappy#9]
The teacher should be able to define own blocks in a way, that his students can achieve difficult tasks in a easy way.

E. g. when he wants his students to program a jump and run game, he makes some blocks like "Jump, Move right/levt, Fall" so that the students can use them.

**Comment by FynnMazurkiewicz** [comment]
I very much agree with this suggestion, we should consider making it a Milestone 1.0 issue.

**Comment by AhmedSoli** [comment]
This already exists. 
Here is an example on how to define the movement circle.

1. Right click anywhere in the script tab.
2. Choose make a block.
3. Pick Motion & command.
4. Type the name of the new command (Circle)
5. Now you see a window where you can define what this block does using other already existing blocks.

**Comment by AhmedSoli** [comment]
Check this out: https://github.com/IT4Kids/Snappy/blob/master/help/addCustomBlock.png

**Comment by FynnMazurkiewicz** [comment]
Thanks for the heads-up! Maybe we should make this feature more obvious?

**Comment by AhmedSoli** [comment]
Yes that would be helpful for sure. We also need to add a delete button (icon) anywhere to make deleting blocks and shapes easier.
